# Generated by Django 4.0.3 on 2022-04-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='boss',
            new_name='parent',
        ),
    ]
