# Generated by Django 4.0.3 on 2022-06-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='update_date',
        ),
    ]
