# Generated by Django 4.0.3 on 2022-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_alter_item_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='testapp.tag', verbose_name='Tag'),
        ),
    ]
